/**
 * Shared role types and route ACL definitions.
 * This file is NOT a client component so it can be imported from middleware (edge runtime).
 */

export type UserRole = "ADMIN" | "NSM" | "BUM" | "MARKETEER" | "DISTRICT_MANAGER" | "MEDICAL_REP" | "ACCOUNTANT" | "WAREHOUSE" | "HR";

// Each route is identified by href; these are the ACLs per role.
// ADMIN always has full access and can override per-user in settings.
export const ROLE_ROUTES: Record<UserRole, string[]> = {
  ADMIN: ["*"],
  NSM: [
    "/dashboard", "/messages", "/tasks",
    "/hubs/crm", "/hubs/quality",
    "/crm/nsm", "/crm/customer-360", "/crm/loyalty", "/crm/forecasting", "/crm/email",
    "/crm/accounts", "/crm/contacts", "/crm/leads", "/crm/opportunities",
    "/crm/campaigns", "/crm/tickets",
    "/crm/bum", "/crm/marketeer", "/crm/district-manager", "/crm/medical-rep",
    "/crm/business-units", "/crm/territories", "/crm/weekly-plan", "/crm/doctors",
    "/crm/gps-tracking", "/crm/market-requests", "/crm/reports", "/crm/kpis",
    "/crm/call-analysis", "/crm/expenses", "/crm/product-guide",
    "/qaqc", "/qaqc/batch-release", "/qaqc/deviations", "/qaqc/capa",
    "/qaqc/stability-studies", "/qaqc/complaints", "/qaqc/recalls",
    "/compliance", "/safety",
    "/ats/training",
    "/admin/audit-log",
    "/analytics",
    "/reports", "/settings", "/settings/profile",
  ],
  BUM: [
    "/dashboard", "/messages", "/tasks",
    "/hubs/crm",
    "/crm/customer-360",
    "/crm/accounts", "/crm/contacts", "/crm/leads", "/crm/opportunities",
    "/crm/campaigns", "/crm/tickets", "/crm/loyalty",
    "/crm/bum", "/crm/marketeer", "/crm/district-manager", "/crm/medical-rep",
    "/crm/business-units", "/crm/territories", "/crm/weekly-plan", "/crm/doctors",
    "/crm/gps-tracking", "/crm/market-requests", "/crm/reports", "/crm/kpis",
    "/crm/call-analysis", "/crm/expenses", "/crm/product-guide",
    "/compliance", "/safety",
    "/ats/training",
    "/reports", "/settings", "/settings/profile",
  ],
  MARKETEER: [
    "/dashboard", "/messages", "/tasks",
    "/hubs/crm",
    "/crm/customer-360",
    "/crm/accounts", "/crm/contacts", "/crm/leads", "/crm/opportunities",
    "/crm/campaigns", "/crm/tickets", "/crm/loyalty",
    "/crm/marketeer", "/crm/district-manager", "/crm/medical-rep",
    "/crm/business-units", "/crm/territories", "/crm/weekly-plan", "/crm/doctors",
    "/crm/gps-tracking", "/crm/market-requests", "/crm/reports", "/crm/kpis",
    "/crm/call-analysis", "/crm/expenses",
    "/ats/training",
    "/settings", "/settings/profile",
  ],
  DISTRICT_MANAGER: [
    "/dashboard", "/messages", "/tasks",
    "/hubs/crm",
    "/crm/customer-360",
    "/crm/accounts", "/crm/contacts", "/crm/tickets",
    "/crm/district-manager", "/crm/medical-rep",
    "/crm/weekly-plan", "/crm/doctors", "/crm/gps-tracking", "/crm/market-requests",
    "/crm/reports", "/crm/kpis", "/crm/call-analysis", "/crm/expenses",
    "/ats/training",
    "/settings", "/settings/profile",
  ],
  MEDICAL_REP: [
    "/dashboard", "/messages", "/tasks",
    "/hubs/crm",
    "/crm/customer-360",
    "/crm/accounts", "/crm/contacts", "/crm/tickets",
    "/crm/medical-rep", "/crm/territories", "/crm/weekly-plan", "/crm/doctors",
    "/crm/gps-tracking", "/crm/market-requests", "/crm/kpis", "/crm/expenses",
    "/ats/training",
    "/settings", "/settings/profile",
  ],
  ACCOUNTANT: [
    "/dashboard", "/messages", "/tasks",
    "/hubs/finance", "/hubs/supply-chain",
    "/erp/finance", "/erp/accounting", "/erp/collections", "/erp/returns",
    "/erp/partner-ledger", "/erp/partner-detail", "/erp/assets", "/erp/banking",
    "/erp/procurement", "/erp/sales-order", "/erp/products", "/erp/e-invoicing",
    "/reports", "/settings", "/settings/profile",
  ],
  WAREHOUSE: [
    "/dashboard", "/messages", "/tasks",
    "/hubs/supply-chain",
    "/erp/inventory", "/erp/products", "/erp/procurement", "/erp/sales-order", "/erp/returns",
    "/erp/manufacturing",
    "/qaqc", "/qaqc/batch-release", "/qaqc/environmental-monitoring",
    "/supply-chain",
    "/settings/profile",
  ],
  HR: [
    "/dashboard", "/messages", "/tasks",
    "/hubs/hr",
    "/erp/hr",
    "/ats/jobs", "/ats/candidates", "/ats/interviews", "/ats/onboarding", "/ats/training",
    "/ats/careers", "/ats/resume-parser",
    "/crm/expenses",
    "/compliance",
    "/settings", "/settings/profile",
  ],
};
