import { IndustryTemplate } from '../types';

export const hospitalityTemplate: IndustryTemplate = {
  id: 'hospitality',
  name: 'Hospitality & Hotels',
  description: 'Property management, reservations, F&B, housekeeping, and guest services for hotels and resorts.',
  icon: 'Hotel',
  modules: [
    'FI', 'CO', 'MM', 'HR',
    'PMS', 'RESERVATIONS', 'FNB', 'HOUSEKEEPING',
    'GUEST_SERVICES', 'LOYALTY', 'FACILITY',
    'CRM', 'REVENUE_MANAGEMENT',
  ],
  orgTemplate: [
    {
      id: 'company',
      type: 'COMPANY',
      code: 'HTL',
      name: 'Hotel Group',
      level: 0,
      isActive: true,
      children: [
        {
          id: 'property-1',
          type: 'PROPERTY',
          code: 'PROP01',
          name: 'City Center Hotel',
          level: 1,
          isActive: true,
          metadata: { roomCount: 200, stars: 5, category: 'luxury' },
          children: [
            { id: 'dept-front', type: 'DEPARTMENT', code: 'FRONT', name: 'Front Office', level: 2, isActive: true },
            { id: 'dept-hk', type: 'DEPARTMENT', code: 'HK', name: 'Housekeeping', level: 2, isActive: true },
            { id: 'dept-fnb', type: 'DEPARTMENT', code: 'FNB', name: 'Food & Beverage', level: 2, isActive: true },
            { id: 'dept-spa', type: 'DEPARTMENT', code: 'SPA', name: 'Spa & Wellness', level: 2, isActive: true },
            { id: 'dept-maint', type: 'DEPARTMENT', code: 'MAINT', name: 'Maintenance', level: 2, isActive: true },
          ],
        },
        {
          id: 'property-2',
          type: 'PROPERTY',
          code: 'PROP02',
          name: 'Beach Resort',
          level: 1,
          isActive: true,
          metadata: { roomCount: 150, stars: 5, category: 'resort' },
        },
      ],
    },
  ],
  customFields: [
    { entityType: 'room', field: 'roomType', label: 'Room Type', type: 'select', options: [
      { label: 'Standard', value: 'standard' },
      { label: 'Superior', value: 'superior' },
      { label: 'Deluxe', value: 'deluxe' },
      { label: 'Suite', value: 'suite' },
      { label: 'Presidential Suite', value: 'presidential' },
    ]},
    { entityType: 'room', field: 'rateCode', label: 'Rate Code', type: 'string' },
    { entityType: 'room', field: 'bedConfiguration', label: 'Bed Configuration', type: 'select', options: [
      { label: 'King', value: 'king' },
      { label: 'Twin', value: 'twin' },
      { label: 'Double', value: 'double' },
      { label: 'Triple', value: 'triple' },
    ]},
    { entityType: 'room', field: 'amenities', label: 'Room Amenities', type: 'multi-select', options: [
      { label: 'Sea View', value: 'sea_view' },
      { label: 'Balcony', value: 'balcony' },
      { label: 'Jacuzzi', value: 'jacuzzi' },
      { label: 'Mini Bar', value: 'minibar' },
      { label: 'Kitchenette', value: 'kitchenette' },
    ]},
    { entityType: 'guest', field: 'vipStatus', label: 'VIP Status', type: 'select', options: [
      { label: 'Regular', value: 'regular' },
      { label: 'VIP', value: 'vip' },
      { label: 'VVIP', value: 'vvip' },
      { label: 'Diplomat', value: 'diplomat' },
    ]},
    { entityType: 'guest', field: 'preferences', label: 'Guest Preferences', type: 'json' },
    { entityType: 'guest', field: 'loyaltyTier', label: 'Loyalty Tier', type: 'select', options: [
      { label: 'Member', value: 'member' },
      { label: 'Silver', value: 'silver' },
      { label: 'Gold', value: 'gold' },
      { label: 'Platinum', value: 'platinum' },
      { label: 'Diamond', value: 'diamond' },
    ]},
  ],
  workflowTemplates: [
    {
      id: 'guest-lifecycle',
      name: 'Guest Stay Lifecycle',
      description: 'Complete guest journey from reservation to post-stay feedback',
      trigger: { type: 'entity_create', entity: 'reservation' },
      steps: [
        { id: 'confirm', type: 'notification', name: 'Send Confirmation', config: { template: 'reservation-confirmed', channel: 'email' }, nextSteps: ['pre-arrival'] },
        { id: 'pre-arrival', type: 'delay', name: 'Wait Until Day Before', config: { until: 'checkInDate', offset: '-1d' }, nextSteps: ['prepare'] },
        { id: 'prepare', type: 'parallel', name: 'Pre-Arrival Prep', config: { }, nextSteps: ['prep-room', 'prep-amenities', 'prep-preferences'] },
        { id: 'prep-room', type: 'action', name: 'Assign Room', config: { action: 'assignRoom' }, nextSteps: ['checkin'] },
        { id: 'prep-amenities', type: 'action', name: 'Prepare Amenities', config: { action: 'prepareAmenities' }, nextSteps: ['checkin'] },
        { id: 'prep-preferences', type: 'action', name: 'Apply Preferences', config: { action: 'applyGuestPreferences' }, nextSteps: ['checkin'] },
        { id: 'checkin', type: 'action', name: 'Check-in', config: { action: 'checkIn' }, nextSteps: ['during-stay'] },
        { id: 'during-stay', type: 'delay', name: 'During Stay', config: { until: 'checkOutDate' }, nextSteps: ['checkout'] },
        { id: 'checkout', type: 'action', name: 'Check-out & Billing', config: { action: 'checkOut' }, nextSteps: ['feedback'] },
        { id: 'feedback', type: 'notification', name: 'Request Feedback', config: { template: 'post-stay-survey', channel: 'email', delay: '24h' }, nextSteps: [] },
      ],
    },
    {
      id: 'housekeeping-workflow',
      name: 'Housekeeping Room Turn',
      description: 'Room cleaning and inspection workflow after checkout',
      trigger: { type: 'status_change', entity: 'room', condition: { status: 'CHECKED_OUT' } },
      steps: [
        { id: 'assign-hk', type: 'action', name: 'Assign to Housekeeper', config: { action: 'assignHousekeeper' }, nextSteps: ['clean'] },
        { id: 'clean', type: 'approval', name: 'Clean Room', config: { role: 'HOUSEKEEPER', timeout: '2h' }, nextSteps: ['inspect'] },
        { id: 'inspect', type: 'approval', name: 'Supervisor Inspection', config: { role: 'HK_SUPERVISOR', timeout: '1h' }, nextSteps: ['ready'], onReject: 'clean' },
        { id: 'ready', type: 'action', name: 'Mark Room Ready', config: { action: 'updateRoomStatus', status: 'READY' }, nextSteps: [] },
      ],
    },
  ],
  terminology: {
    'customer': 'Guest',
    'product': 'Service',
    'warehouse': 'Store Room',
    'plant': 'Property',
    'invoice': 'Folio',
    'work_order': 'Service Request',
    'employee': 'Team Member',
    'department': 'Department',
  },
  compliance: [
    { id: 'health-safety', standard: 'Health & Safety', requirement: 'Guest Safety', description: 'Health and safety regulations for hospitality establishments', controls: ['fire-safety', 'food-safety', 'pool-safety', 'emergency-procedures'], evidenceTypes: ['inspection-report', 'drill-record', 'certification'] },
    { id: 'haccp', standard: 'HACCP', requirement: 'Food Safety', description: 'Hazard Analysis Critical Control Points for F&B operations', controls: ['temperature-monitoring', 'hygiene-practices', 'allergen-management', 'traceability'], evidenceTypes: ['temperature-log', 'hygiene-audit', 'allergen-chart'] },
    { id: 'gdpr-hospitality', standard: 'GDPR', requirement: 'Guest Data Privacy', description: 'Data protection for guest personal information', controls: ['consent-management', 'data-retention', 'right-to-erasure', 'data-minimization'], evidenceTypes: ['consent-record', 'retention-policy', 'erasure-log'] },
  ],
};
