import { IndustryTemplate } from '../types';

export const pharmaceuticalTemplate: IndustryTemplate = {
  id: 'pharmaceutical',
  name: 'Pharmaceutical & Life Sciences',
  description: 'Complete GxP-compliant ERP for pharmaceutical manufacturing, quality control, and regulatory compliance.',
  icon: 'Pill',
  modules: [
    'FI', 'CO', 'MM', 'SD', 'PP', 'QM', 'PM', 'HR',
    'QAQC_AUDIT', 'QAQC_BATCH_RELEASE', 'QAQC_CAPA', 'QAQC_CHANGE_CONTROL',
    'QAQC_CLEANING_VALIDATION', 'QAQC_COMPLAINTS', 'QAQC_DEVIATIONS',
    'QAQC_DOCUMENT_CONTROL', 'QAQC_ENVIRONMENTAL', 'QAQC_OOS',
    'QAQC_RECALLS', 'QAQC_RISK', 'QAQC_SPC', 'QAQC_STABILITY',
    'QAQC_TRAINING', 'QAQC_WATER_SYSTEM',
    'CRM', 'ATS', 'MFG_BATCH_RECORDS',
  ],
  orgTemplate: [
    {
      id: 'company',
      type: 'COMPANY',
      code: 'PHARMA',
      name: 'Pharmaceutical Company',
      level: 0,
      isActive: true,
      children: [
        {
          id: 'plant-main',
          type: 'PLANT',
          code: 'PLANT01',
          name: 'Main Manufacturing Plant',
          level: 1,
          isActive: true,
          children: [
            { id: 'sl-rm', type: 'STORAGE_LOCATION', code: 'SL-RM', name: 'Raw Materials Warehouse', level: 2, isActive: true },
            { id: 'sl-fp', type: 'STORAGE_LOCATION', code: 'SL-FP', name: 'Finished Products Warehouse', level: 2, isActive: true },
            { id: 'sl-qr', type: 'STORAGE_LOCATION', code: 'SL-QR', name: 'Quarantine Area', level: 2, isActive: true },
            { id: 'sl-cc', type: 'STORAGE_LOCATION', code: 'SL-CC', name: 'Cold Chain Storage', level: 2, isActive: true },
          ],
        },
        {
          id: 'plant-qa',
          type: 'PLANT',
          code: 'QC-LAB',
          name: 'Quality Control Laboratory',
          level: 1,
          isActive: true,
        },
        {
          id: 'sales-org',
          type: 'SALES_ORG',
          code: 'SO01',
          name: 'Domestic Sales Organization',
          level: 1,
          isActive: true,
          children: [
            { id: 'dc-hospital', type: 'DISTRIBUTION_CHANNEL', code: 'DC-HOSP', name: 'Hospital Channel', level: 2, isActive: true },
            { id: 'dc-pharmacy', type: 'DISTRIBUTION_CHANNEL', code: 'DC-PHAR', name: 'Pharmacy Channel', level: 2, isActive: true },
            { id: 'dc-tender', type: 'DISTRIBUTION_CHANNEL', code: 'DC-TEND', name: 'Government Tenders', level: 2, isActive: true },
          ],
        },
      ],
    },
  ],
  customFields: [
    { entityType: 'product', field: 'edaRegistration', label: 'EDA Registration Number', type: 'string' },
    { entityType: 'product', field: 'therapeuticArea', label: 'Therapeutic Area', type: 'select', options: [
      { label: 'Cardiovascular', value: 'cardiovascular' },
      { label: 'Respiratory', value: 'respiratory' },
      { label: 'Oncology', value: 'oncology' },
      { label: 'Neurology', value: 'neurology' },
      { label: 'Anti-infectives', value: 'anti-infectives' },
      { label: 'Gastrointestinal', value: 'gastrointestinal' },
    ]},
    { entityType: 'product', field: 'gmpClassification', label: 'GMP Classification', type: 'select', options: [
      { label: 'Sterile', value: 'sterile' },
      { label: 'Non-Sterile', value: 'non-sterile' },
      { label: 'Biological', value: 'biological' },
    ]},
    { entityType: 'product', field: 'shelfLife', label: 'Shelf Life (months)', type: 'number' },
    { entityType: 'product', field: 'storageCondition', label: 'Storage Condition', type: 'select', options: [
      { label: 'Room Temperature (15-25°C)', value: 'room_temp' },
      { label: 'Refrigerated (2-8°C)', value: 'refrigerated' },
      { label: 'Frozen (-20°C)', value: 'frozen' },
      { label: 'Deep Frozen (-80°C)', value: 'deep_frozen' },
    ]},
    { entityType: 'customer', field: 'buyingLadder', label: 'Buying Ladder Stage', type: 'select', options: [
      { label: 'Awareness', value: 'awareness' },
      { label: 'Interest', value: 'interest' },
      { label: 'Trial', value: 'trial' },
      { label: 'Adoption', value: 'adoption' },
      { label: 'Loyalty', value: 'loyalty' },
    ]},
    { entityType: 'customer', field: 'specialty', label: 'Medical Specialty', type: 'string' },
    { entityType: 'batch', field: 'cleanRoomClass', label: 'Clean Room Classification', type: 'select', options: [
      { label: 'Class A', value: 'class_a' },
      { label: 'Class B', value: 'class_b' },
      { label: 'Class C', value: 'class_c' },
      { label: 'Class D', value: 'class_d' },
    ]},
  ],
  workflowTemplates: [
    {
      id: 'batch-release-workflow',
      name: 'Batch Release Workflow',
      description: 'GMP-compliant batch release with QC testing, QA review, and QP release',
      trigger: { type: 'status_change', entity: 'batchRelease', condition: { status: 'UNDER_REVIEW' } },
      steps: [
        { id: 'qc-review', type: 'approval', name: 'QC Lab Review', config: { role: 'QC_MANAGER', timeout: '48h' }, nextSteps: ['qa-review'], onReject: 'reject-batch' },
        { id: 'qa-review', type: 'approval', name: 'QA Review', config: { role: 'QA_MANAGER', timeout: '24h', requireSignature: true }, nextSteps: ['qp-release'], onReject: 'reject-batch' },
        { id: 'qp-release', type: 'approval', name: 'Qualified Person Release', config: { role: 'QUALIFIED_PERSON', timeout: '24h', requireSignature: true }, nextSteps: ['release-complete'] },
        { id: 'release-complete', type: 'action', name: 'Update Batch Status', config: { action: 'updateStatus', entity: 'batchRelease', status: 'APPROVED' }, nextSteps: [] },
        { id: 'reject-batch', type: 'action', name: 'Reject Batch', config: { action: 'updateStatus', entity: 'batchRelease', status: 'REJECTED', createDeviation: true }, nextSteps: [] },
      ],
    },
    {
      id: 'capa-workflow',
      name: 'CAPA Workflow',
      description: 'Corrective and Preventive Action lifecycle management',
      trigger: { type: 'entity_create', entity: 'capa' },
      steps: [
        { id: 'assign', type: 'notification', name: 'Notify Assignee', config: { template: 'capa-assigned' }, nextSteps: ['investigate'] },
        { id: 'investigate', type: 'approval', name: 'Root Cause Investigation', config: { role: 'ASSIGNEE', timeout: '7d' }, nextSteps: ['plan'] },
        { id: 'plan', type: 'approval', name: 'Action Plan Approval', config: { role: 'QA_MANAGER', timeout: '3d' }, nextSteps: ['implement'] },
        { id: 'implement', type: 'approval', name: 'Implementation Verification', config: { role: 'ASSIGNEE', timeout: '30d' }, nextSteps: ['verify'] },
        { id: 'verify', type: 'approval', name: 'Effectiveness Check', config: { role: 'QA_MANAGER', timeout: '14d', requireSignature: true }, nextSteps: ['close'] },
        { id: 'close', type: 'action', name: 'Close CAPA', config: { action: 'updateStatus', entity: 'capa', status: 'CLOSED' }, nextSteps: [] },
      ],
    },
    {
      id: 'deviation-workflow',
      name: 'Deviation Management Workflow',
      description: 'Deviation investigation and resolution with optional CAPA creation',
      trigger: { type: 'entity_create', entity: 'deviation' },
      steps: [
        { id: 'notify', type: 'notification', name: 'Alert QA Team', config: { template: 'deviation-reported', roles: ['QA_MANAGER'] }, nextSteps: ['investigate'] },
        { id: 'investigate', type: 'approval', name: 'Investigation', config: { role: 'QA_ANALYST', timeout: '5d' }, nextSteps: ['assess'] },
        { id: 'assess', type: 'condition', name: 'Assess CAPA Need', config: { field: 'severity', operator: 'in', value: ['CRITICAL', 'MAJOR'] }, nextSteps: ['create-capa'], onReject: 'close' },
        { id: 'create-capa', type: 'action', name: 'Create CAPA', config: { action: 'createEntity', entity: 'capa', source: 'deviation' }, nextSteps: ['close'] },
        { id: 'close', type: 'action', name: 'Close Deviation', config: { action: 'updateStatus', entity: 'deviation', status: 'CLOSED' }, nextSteps: [] },
      ],
    },
  ],
  terminology: {
    'customer': 'Healthcare Provider',
    'contact': 'Doctor',
    'appointment': 'Visit',
    'deal': 'Tender',
    'product': 'Drug Product',
    'warehouse': 'Storage Area',
    'quality_check': 'In-Process Control',
    'supplier': 'API/Excipient Supplier',
  },
  compliance: [
    { id: 'cfr-21-11', standard: '21 CFR Part 11', requirement: 'Electronic Records and Signatures', description: 'FDA regulation for electronic records requiring audit trails, access controls, and electronic signatures', controls: ['audit-trail', 'e-signature', 'access-control', 'data-integrity'], evidenceTypes: ['system-log', 'validation-report', 'user-access-matrix'] },
    { id: 'eu-gmp-annex-11', standard: 'EU GMP Annex 11', requirement: 'Computerised Systems', description: 'European GMP requirements for computerized systems in pharmaceutical manufacturing', controls: ['validation', 'change-control', 'business-continuity', 'data-integrity'], evidenceTypes: ['validation-protocol', 'change-control-record', 'backup-log'] },
    { id: 'ich-q10', standard: 'ICH Q10', requirement: 'Pharmaceutical Quality System', description: 'International guidelines for pharmaceutical quality systems', controls: ['capa', 'change-management', 'management-review', 'continual-improvement'], evidenceTypes: ['capa-record', 'management-review-minutes', 'kpi-report'] },
    { id: 'gdp', standard: 'GDP (Good Distribution Practice)', requirement: 'Pharmaceutical Distribution', description: 'Guidelines for proper distribution of medicinal products', controls: ['temperature-monitoring', 'traceability', 'transportation-validation'], evidenceTypes: ['temperature-log', 'distribution-record', 'transport-validation'] },
  ],
};
