import { IndustryTemplate } from '../types';

export const professionalServicesTemplate: IndustryTemplate = {
  id: 'professional-services',
  name: 'Professional Services',
  description: 'Project-based ERP for consulting, IT services, legal, and engineering firms with time tracking and resource management.',
  icon: 'Briefcase',
  modules: [
    'FI', 'CO', 'HR',
    'PROJECT_BILLING', 'TIME_TRACKING', 'RESOURCE_MANAGEMENT',
    'SLA_MANAGEMENT', 'CONTRACT_MANAGEMENT',
    'CRM', 'HELPDESK',
  ],
  orgTemplate: [
    {
      id: 'company',
      type: 'COMPANY',
      code: 'SVC',
      name: 'Services Company',
      level: 0,
      isActive: true,
      children: [
        {
          id: 'practice-consulting',
          type: 'DEPARTMENT',
          code: 'CONS',
          name: 'Consulting Practice',
          level: 1,
          isActive: true,
          children: [
            { id: 'team-strategy', type: 'TEAM', code: 'STRAT', name: 'Strategy Team', level: 2, isActive: true },
            { id: 'team-ops', type: 'TEAM', code: 'OPS', name: 'Operations Team', level: 2, isActive: true },
          ],
        },
        {
          id: 'practice-tech',
          type: 'DEPARTMENT',
          code: 'TECH',
          name: 'Technology Practice',
          level: 1,
          isActive: true,
          children: [
            { id: 'team-dev', type: 'TEAM', code: 'DEV', name: 'Development Team', level: 2, isActive: true },
            { id: 'team-infra', type: 'TEAM', code: 'INFRA', name: 'Infrastructure Team', level: 2, isActive: true },
          ],
        },
        {
          id: 'practice-managed',
          type: 'DEPARTMENT',
          code: 'MGSD',
          name: 'Managed Services',
          level: 1,
          isActive: true,
        },
      ],
    },
  ],
  customFields: [
    { entityType: 'project', field: 'billingModel', label: 'Billing Model', type: 'select', options: [
      { label: 'Time & Material', value: 'time_material' },
      { label: 'Fixed Price', value: 'fixed_price' },
      { label: 'Retainer', value: 'retainer' },
      { label: 'Milestone-Based', value: 'milestone' },
    ]},
    { entityType: 'project', field: 'utilizationTarget', label: 'Utilization Target (%)', type: 'number', defaultValue: 80 },
    { entityType: 'project', field: 'engagementManager', label: 'Engagement Manager', type: 'string' },
    { entityType: 'employee', field: 'billableRate', label: 'Billable Rate ($/hr)', type: 'number' },
    { entityType: 'employee', field: 'costRate', label: 'Cost Rate ($/hr)', type: 'number' },
    { entityType: 'employee', field: 'skills', label: 'Skills', type: 'multi-select', options: [
      { label: 'Project Management', value: 'pm' },
      { label: 'Solution Architecture', value: 'arch' },
      { label: 'Development', value: 'dev' },
      { label: 'Cloud/DevOps', value: 'cloud' },
      { label: 'Data Analytics', value: 'data' },
      { label: 'Change Management', value: 'change' },
    ]},
    { entityType: 'employee', field: 'certifications', label: 'Certifications', type: 'multi-select', options: [
      { label: 'PMP', value: 'pmp' },
      { label: 'AWS Solutions Architect', value: 'aws_sa' },
      { label: 'ITIL', value: 'itil' },
      { label: 'Scrum Master', value: 'csm' },
    ]},
    { entityType: 'contract', field: 'slaLevel', label: 'SLA Level', type: 'select', options: [
      { label: 'Platinum (99.99%)', value: 'platinum' },
      { label: 'Gold (99.9%)', value: 'gold' },
      { label: 'Silver (99.5%)', value: 'silver' },
      { label: 'Bronze (99%)', value: 'bronze' },
    ]},
  ],
  workflowTemplates: [
    {
      id: 'engagement-lifecycle',
      name: 'Engagement Lifecycle',
      description: 'Client engagement from proposal to close-out',
      trigger: { type: 'entity_create', entity: 'engagement' },
      steps: [
        { id: 'qualify', type: 'approval', name: 'Opportunity Qualification', config: { role: 'PARTNER', timeout: '3d' }, nextSteps: ['propose'] },
        { id: 'propose', type: 'action', name: 'Create Proposal', config: { action: 'createProposal' }, nextSteps: ['client-review'] },
        { id: 'client-review', type: 'approval', name: 'Client Approval', config: { role: 'CLIENT', timeout: '14d' }, nextSteps: ['staff'], onReject: 'revise' },
        { id: 'revise', type: 'action', name: 'Revise Proposal', config: { action: 'reviseProposal' }, nextSteps: ['client-review'] },
        { id: 'staff', type: 'action', name: 'Resource Allocation', config: { action: 'allocateResources' }, nextSteps: ['kickoff'] },
        { id: 'kickoff', type: 'notification', name: 'Project Kickoff', config: { template: 'engagement-kickoff' }, nextSteps: ['execute'] },
        { id: 'execute', type: 'action', name: 'Delivery Phase', config: { action: 'startDelivery' }, nextSteps: ['review'] },
        { id: 'review', type: 'approval', name: 'Client Sign-off', config: { role: 'CLIENT', timeout: '7d' }, nextSteps: ['close'] },
        { id: 'close', type: 'action', name: 'Close Engagement', config: { action: 'closeEngagement' }, nextSteps: [] },
      ],
    },
    {
      id: 'timesheet-approval',
      name: 'Weekly Timesheet Approval',
      description: 'Weekly timesheet submission and approval workflow',
      trigger: { type: 'schedule', schedule: '0 9 * * 1' },
      steps: [
        { id: 'remind', type: 'notification', name: 'Submit Timesheet Reminder', config: { template: 'timesheet-reminder', roles: ['CONSULTANT'] }, nextSteps: ['wait'] },
        { id: 'wait', type: 'delay', name: 'Wait for Submission', config: { duration: '24h' }, nextSteps: ['approve'] },
        { id: 'approve', type: 'approval', name: 'Manager Approval', config: { role: 'ENGAGEMENT_MANAGER', timeout: '48h' }, nextSteps: ['bill'], onReject: 'revise' },
        { id: 'revise', type: 'notification', name: 'Request Revision', config: { template: 'timesheet-revision' }, nextSteps: ['wait'] },
        { id: 'bill', type: 'action', name: 'Generate Invoice Items', config: { action: 'generateBillingItems' }, nextSteps: [] },
      ],
    },
  ],
  terminology: {
    'customer': 'Client',
    'product': 'Service Offering',
    'project': 'Engagement',
    'employee': 'Resource',
    'work_order': 'Work Package',
    'invoice': 'Invoice',
    'department': 'Practice',
    'team': 'Team',
  },
  compliance: [
    { id: 'soc2', standard: 'SOC 2 Type II', requirement: 'Service Organization Controls', description: 'Trust service criteria for service organizations', controls: ['access-control', 'encryption', 'monitoring', 'change-management', 'risk-assessment'], evidenceTypes: ['audit-report', 'access-review', 'change-log', 'risk-register'] },
    { id: 'iso-27001', standard: 'ISO 27001:2022', requirement: 'Information Security Management', description: 'ISMS requirements for protecting client data', controls: ['asset-management', 'access-control', 'cryptography', 'operations-security', 'incident-management'], evidenceTypes: ['isms-manual', 'risk-treatment-plan', 'incident-record', 'internal-audit'] },
  ],
};
