#!/usr/bin/env bash
# Generate docs/salvage/01-schema-reference.md from prisma/schema.prisma.
#
# For Phase 1 kernel design: the new system will not use this schema
# directly, but every model in it captures a domain decision worth
# referencing. Re-run after schema changes for an updated baseline.
#
# Output: a Markdown document with one section per model, listing
# fields, relations, indexes, and the SQL table name.

set -euo pipefail
cd "$(dirname "$0")/.."

OUT=docs/salvage/01-schema-reference.md
mkdir -p docs/salvage

{
  cat <<'EOF'
# Phase 0 Salvage — Schema Reference

> AUTO-GENERATED by `scripts/salvage-schema.sh` from `prisma/schema.prisma`.
> Don't edit by hand. Re-run to regenerate.

This file captures the **domain decomposition** of the ERP repo at the
point it was archived. The Phase 1 kernel will not import this schema
directly — but each model here represents one or more design decisions
about the business domain (Egyptian pharma ERP), and those decisions
are worth referencing when designing Phase 1 modules.

## How to use this in Phase 1

- Use the model list as a **domain map**. Each model = one bounded
  concept. Decide which modules in Phase 1 own which models.
- Pull field shapes when scaffolding equivalent Phase 1 tables. The
  field types and indexes encode real-world experience.
- The `tenantId` column on every model (added in Phase 0 Track B2.1)
  is the multi-tenancy contract — preserve it.
- Enums (separate doc: `02-domain-vocabulary.md`) capture business
  states; copy them verbatim into Phase 1 unless you have a reason to
  rename.

## Model index

EOF

  # Print a sorted index with @@map table names
  awk '
    /^model / {
      model = $2
      in_model = 1
      table = ""
      next
    }
    /^}/ && in_model {
      if (table == "") table = model
      print model "|" table
      in_model = 0
      next
    }
    in_model && /^[[:space:]]+@@map\(/ {
      n = split($0, parts, "\"")
      if (n >= 2) table = parts[2]
    }
  ' prisma/schema.prisma | sort | while IFS='|' read -r model table; do
    anchor="$(echo "$model" | tr '[:upper:]' '[:lower:]')"
    echo "- [\`$model\`](#$anchor) → table \`$table\`"
  done

  echo ""
  echo "## Models"
  echo ""

  # Now emit one section per model, in alphabetical order
  awk '
    /^model / {
      model = $2
      in_model = 1
      table = ""
      buf = ""
      next
    }
    /^}/ && in_model {
      if (table == "") table = model
      print "===MODEL===" model "|" table
      print buf
      print "===END==="
      in_model = 0
      buf = ""
      next
    }
    in_model {
      buf = buf $0 "\n"
    }
  ' prisma/schema.prisma | awk '
    BEGIN { collecting = 0; sections_count = 0 }
    /^===MODEL===/ {
      n = split($0, a, "===MODEL===")
      header = a[2]
      m_split = split(header, parts, "|")
      sections[sections_count, "model"] = parts[1]
      sections[sections_count, "table"] = parts[2]
      sections[sections_count, "body"] = ""
      collecting = 1
      next
    }
    /^===END===/ {
      collecting = 0
      sections_count++
      next
    }
    collecting {
      sections[sections_count - 0 + (collecting == 1 ? 0 : 0), "body"] = sections[sections_count, "body"] $0 "\n"
    }
    END {
      # Sort by model name
      for (i = 0; i < sections_count; i++) models[i] = sections[i, "model"]
      # bubble sort (small N)
      for (i = 0; i < sections_count; i++)
        for (j = i + 1; j < sections_count; j++)
          if (models[i] > models[j]) {
            t = models[i]; models[i] = models[j]; models[j] = t
            for (k in sections) {
              if (k ~ "^"i",") {
                key_suffix = k
                sub("^"i",", "", key_suffix)
                t2 = sections[i, key_suffix]
                sections[i, key_suffix] = sections[j, key_suffix]
                sections[j, key_suffix] = t2
              }
            }
          }
      # Emit
      for (i = 0; i < sections_count; i++) {
        m = sections[i, "model"]
        t = sections[i, "table"]
        anchor = tolower(m)
        printf "### %s\n\n", m
        printf "- **Table:** `%s`\n", t
        printf "- **Definition:**\n\n"
        printf "```prisma\nmodel %s {\n%s}\n```\n\n", m, sections[i, "body"]
      }
    }
  '
} > "$OUT"

echo "Wrote $OUT"
wc -l "$OUT"
