#!/usr/bin/env tsx
/**
 * Generates a fresh tenant-scoped CRUD route from the Prisma schema.
 *
 * Used to replace REWRITE-bucket routes (per docs/PHASE0_TRACK_B_TRIAGE.md)
 * whose current implementation references models that don't exist or is
 * otherwise broken beyond migration.
 *
 * Reads:
 *   - The target model from `prisma/schema.prisma`
 *   - Its field list to seed validation
 *   - Its @@map for the SQL table name (informational only)
 *
 * Writes:
 *   - src/app/api/<path>/route.ts        (list + create)
 *   - src/app/api/<path>/[id]/route.ts   (read + update + delete)
 *
 * Output uses `createRouteHandlers` from route-factory, so tenant
 * isolation is inherited automatically (no custom wrapper code per
 * scaffolded route).
 *
 * Usage:
 *   npx tsx scripts/scaffold-route.ts \
 *     --model Invoice \
 *     --path /api/v1/finance/invoices
 *
 *   npx tsx scripts/scaffold-route.ts --help
 *
 * The generator deliberately produces minimal code:
 *   - Pagination, search, basic filters via the factory's standard surface.
 *   - Validation imports a zod schema if `--validations` is provided;
 *     otherwise scaffolds a TODO placeholder.
 *   - Per-route customizations (hooks, allowedIncludes, defaultSort)
 *     are added by hand after scaffolding.
 *
 * Status: SKELETON. Output is intentionally small so the operator can
 * read and adapt it. Heuristic field detection is regex-based; verify
 * the emitted route against the schema before committing.
 */

import * as fs from "node:fs";
import * as path from "node:path";

const REPO_ROOT = path.resolve(__dirname, "..");
const SCHEMA = path.join(REPO_ROOT, "prisma", "schema.prisma");

interface CliArgs {
  model?: string;
  apiPath?: string;
  validations?: string;
  help?: boolean;
  force?: boolean;
}

function parseArgs(argv: string[]): CliArgs {
  const a: CliArgs = {};
  for (let i = 0; i < argv.length; i++) {
    const cur = argv[i];
    if (cur === "--help" || cur === "-h") a.help = true;
    else if (cur === "--model") a.model = argv[++i];
    else if (cur === "--path") a.apiPath = argv[++i];
    else if (cur === "--validations") a.validations = argv[++i];
    else if (cur === "--force") a.force = true;
  }
  return a;
}

function help() {
  console.log(
    [
      "Usage: scaffold-route.ts --model <Model> --path <apiPath> [--validations <path>] [--force]",
      "",
      "Example:",
      "  npx tsx scripts/scaffold-route.ts --model Invoice --path /api/v1/finance/invoices",
      "",
      "Required flags:",
      "  --model <Name>         PascalCase Prisma model name (must exist in schema)",
      "  --path  <apiPath>      Path relative to src/app, starting with /api",
      "",
      "Optional flags:",
      "  --validations <file>   Path to a TS file exporting createXSchema / updateXSchema",
      "  --force                Overwrite existing route files",
    ].join("\n"),
  );
}

function modelExists(modelName: string): boolean {
  const schema = fs.readFileSync(SCHEMA, "utf8");
  return new RegExp(`^model\\s+${modelName}\\s*\\{`, "m").test(schema);
}

function searchFieldsFor(modelName: string): string[] {
  // Heuristic: pull String fields named name / title / sku / code / number / email / description.
  const schema = fs.readFileSync(SCHEMA, "utf8");
  const start = schema.indexOf(`model ${modelName} {`);
  if (start < 0) return ["name"];
  const end = schema.indexOf("\n}", start);
  const body = schema.slice(start, end);
  const candidates = ["name", "title", "sku", "code", "number", "email", "description"];
  return candidates.filter((c) =>
    new RegExp(`^\\s*${c}\\s+String`, "m").test(body),
  );
}

function camelize(name: string): string {
  return name[0].toLowerCase() + name.slice(1);
}

function pascalToKebab(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase();
}

// ─── Templates ─────────────────────────────────────────────────────────────

function listRouteTemplate(opts: {
  model: string;
  entity: string;
  validationsImport: string;
  validationsKey: string | null;
  searchFields: string[];
}): string {
  return `import { createRouteHandlers } from '@/lib/api/route-factory';
${opts.validationsImport}
// AUTO-GENERATED by scripts/scaffold-route.ts.
// Replaces a non-functional route flagged in docs/PHASE0_TRACK_B_TRIAGE.md.
// Tenant isolation + auth inherited from createRouteHandlers (which uses
// withAuthAndTenant under the hood).

export const { GET, POST } = createRouteHandlers({
  entity: '${opts.entity}',
  modelName: '${camelize(opts.model)}',
  defaultPageSize: 25,
  defaultSort: { field: 'createdAt', direction: 'desc' },
  searchFields: ${JSON.stringify(opts.searchFields)},${
    opts.validationsKey
      ? `\n  validationSchema: {
    create: ${opts.validationsKey}.create,
    update: ${opts.validationsKey}.update,
  },`
      : `\n  // TODO: add validationSchema { create, update } via --validations on a re-scaffold.`
  }
});
`;
}

function idRouteTemplate(opts: {
  model: string;
  entity: string;
  validationsImport: string;
  validationsKey: string | null;
}): string {
  return `import { createRouteHandlersWithId } from '@/lib/api/route-factory';
${opts.validationsImport}
// AUTO-GENERATED by scripts/scaffold-route.ts.

export const { GET, PATCH, DELETE } = createRouteHandlersWithId({
  entity: '${opts.entity}',
  modelName: '${camelize(opts.model)}',${
    opts.validationsKey
      ? `\n  validationSchema: {
    update: ${opts.validationsKey}.update,
  },`
      : `\n  // TODO: add validationSchema.update via --validations on a re-scaffold.`
  }
});
`;
}

// ─── Main ───────────────────────────────────────────────────────────────────

function run() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help || !args.model || !args.apiPath) {
    help();
    process.exit(args.help ? 0 : 1);
  }

  if (!modelExists(args.model!)) {
    console.error(
      `[scaffold] model not found in schema: ${args.model}. Add the model to prisma/schema.prisma first.`,
    );
    process.exit(2);
  }

  const apiPath = args.apiPath!.replace(/^\//, "");
  const baseDir = path.join(REPO_ROOT, "src", "app", apiPath);
  const idDir = path.join(baseDir, "[id]");
  fs.mkdirSync(idDir, { recursive: true });

  const validationsImport = args.validations
    ? `import * as Validations from '${args.validations}';`
    : "";
  const validationsKey = args.validations ? "Validations" : null;

  const entity = pascalToKebab(args.model!);
  const searchFields = searchFieldsFor(args.model!);

  const listFile = path.join(baseDir, "route.ts");
  const idFile = path.join(idDir, "route.ts");

  for (const f of [listFile, idFile]) {
    if (fs.existsSync(f) && !args.force) {
      console.error(`[scaffold] ${f} already exists. Use --force to overwrite.`);
      process.exit(3);
    }
  }

  fs.writeFileSync(
    listFile,
    listRouteTemplate({
      model: args.model!,
      entity,
      validationsImport,
      validationsKey,
      searchFields,
    }),
  );
  fs.writeFileSync(
    idFile,
    idRouteTemplate({
      model: args.model!,
      entity,
      validationsImport,
      validationsKey,
    }),
  );

  console.log(`[scaffold] wrote ${path.relative(REPO_ROOT, listFile)}`);
  console.log(`[scaffold] wrote ${path.relative(REPO_ROOT, idFile)}`);
  console.log(
    `[scaffold] entity=${entity} model=${args.model} fields=${JSON.stringify(searchFields)}`,
  );
}

if (require.main === module) {
  run();
}
