#!/usr/bin/env bash
# Phase 0 Track B — automated route triage.
#
# Classifies every src/app/api/**/route.ts file into one of:
#   BAND-3         — auth/webhook/health/csrf/docs; no tenancy needed.
#   REWRITE        — references a Prisma model that doesn't exist in the
#                    schema, or is otherwise structurally broken.
#   FACTORY        — uses src/lib/api/route-factory.ts (createRouteHandlers).
#                    Migration happens centrally in route-factory.ts; the
#                    route file itself needs no changes.
#   STANDARD       — matches the B3 exemplar pattern (lazy prisma require
#                    + standard helpers + recognizable model reference).
#                    Eligible for the codemod in scripts/migrate-routes.ts.
#   REVIEW         — uses prisma but doesn't match the standard pattern;
#                    needs human inspection before migrating.
#   NO-PRISMA      — has no prisma reference and doesn't use the factory
#                    (proxies, passthroughs, AI-only, mock-only stubs);
#                    needs human inspection.
#
# Output: docs/PHASE0_TRACK_B_TRIAGE.md
#
# Idempotent — safe to re-run after schema or route changes.

set -euo pipefail

cd "$(dirname "$0")/.."

OUT=docs/PHASE0_TRACK_B_TRIAGE.md

# ─── Inputs ────────────────────────────────────────────────────────────────

ROUTES=$(find src/app/api -name "route.ts" | sort)
ROUTE_COUNT=$(echo "$ROUTES" | wc -l)

# Schema model → expected Prisma client property (first-char lowercase).
# Built from schema.prisma so this stays in sync if models are added.
declare -A MODELS
while IFS= read -r model; do
  [ -z "$model" ] && continue
  prop="$(echo "${model:0:1}" | tr '[:upper:]' '[:lower:]')${model:1}"
  MODELS["$prop"]=1
done < <(awk '/^model / { print $2 }' prisma/schema.prisma)

# ─── Per-route classification ──────────────────────────────────────────────

declare -A CATEGORY
declare -A REASON

# Band-3 path prefixes — skip entirely. These routes have intentionally
# no tenant context (auth bootstrap, webhook receivers, docs).
band3_prefixes=(
  "src/app/api/auth/"
  "src/app/api/v1/health"
  "src/app/api/v1/csrf"
  "src/app/api/v1/docs"
  "src/app/api/v1/events"
  "src/app/api/webhooks/"
  "src/app/api/v1/webhooks/"
)

while IFS= read -r route; do
  cat=""
  reason=""

  # Band 3 first
  for p in "${band3_prefixes[@]}"; do
    if [[ "$route" == "$p"* ]]; then
      cat="BAND-3"
      reason="path prefix"
      break
    fi
  done

  if [ -z "$cat" ]; then
    uses_factory=$(grep -c "createRouteHandlers" "$route" || true)
    refs=$(grep -oE "prisma\.[a-zA-Z]+" "$route" | sort -u || true)

    if [ "$uses_factory" -gt 0 ]; then
      model=$(grep -oE "modelName:\s*['\"][a-zA-Z]+['\"]" "$route" | head -1 | sed -E "s/modelName:\s*['\"]([a-zA-Z]+)['\"]/\1/")
      cat="FACTORY"
      reason="uses createRouteHandlers (modelName=${model:-unknown})"
    elif [ -z "$refs" ]; then
      cat="NO-PRISMA"
      reason="no prisma.<model> reference, not a factory route"
    else
      # Unknown-model references?
      unknown=""
      for ref in $refs; do
        prop="${ref#prisma.}"
        if [ -z "${MODELS[$prop]+_}" ]; then
          unknown="$unknown $prop"
        fi
      done

      if [ -n "$unknown" ]; then
        cat="REWRITE"
        reason="references missing model(s):$unknown"
      else
        # Standard B3-pattern detection.
        has_lazy=$(grep -c "let prisma:.*=.*null" "$route" || true)
        has_helpers=$(grep -cE "from \"@/lib/api/api-helpers\"" "$route" || true)
        has_handler=$(grep -cE "export (async function|const) (GET|POST|PUT|PATCH|DELETE)" "$route" || true)

        if [ "$has_lazy" -gt 0 ] && [ "$has_helpers" -gt 0 ] && [ "$has_handler" -gt 0 ]; then
          cat="STANDARD"
          model_list=$(echo "$refs" | tr '\n' ',' | sed 's/,$//')
          reason="lazy-prisma + helpers + handlers; uses $model_list"
        else
          cat="REVIEW"
          missing=""
          [ "$has_lazy" -eq 0 ] && missing="$missing no-lazy-prisma"
          [ "$has_helpers" -eq 0 ] && missing="$missing no-api-helpers"
          [ "$has_handler" -eq 0 ] && missing="$missing no-handler-export"
          reason="prisma used but non-standard shape:$missing"
        fi
      fi
    fi
  fi

  CATEGORY["$route"]="$cat"
  REASON["$route"]="$reason"
done <<< "$ROUTES"

# ─── Counts ────────────────────────────────────────────────────────────────

declare -A COUNTS
for cat in BAND-3 REWRITE FACTORY STANDARD REVIEW NO-PRISMA; do
  COUNTS["$cat"]=0
done
for route in "${!CATEGORY[@]}"; do
  c="${CATEGORY[$route]}"
  COUNTS["$c"]=$((${COUNTS["$c"]} + 1))
done

# ─── Emit report ───────────────────────────────────────────────────────────

{
  echo "# Phase 0 Track B — automated route triage"
  echo ""
  echo "> Generated by \`scripts/triage-routes.sh\`. Re-run on schema or route changes."
  echo "> Date: $(date +%Y-%m-%d)"
  echo ""
  echo "## Summary"
  echo ""
  echo "| Category | Count | Action |"
  echo "|---|---|---|"
  echo "| **FACTORY** | ${COUNTS[FACTORY]} | Migrate \`src/lib/api/route-factory.ts\` once; all factory routes inherit |"
  echo "| **STANDARD** | ${COUNTS[STANDARD]} | Run codemod (\`scripts/migrate-routes.ts\`); land per-folder PRs |"
  echo "| **REWRITE** | ${COUNTS[REWRITE]} | Generate fresh route from template; current code is broken |"
  echo "| **REVIEW** | ${COUNTS[REVIEW]} | Human inspection before migration |"
  echo "| **NO-PRISMA** | ${COUNTS[NO-PRISMA]} | Human inspection; usually proxies / passthroughs |"
  echo "| **BAND-3** | ${COUNTS[BAND-3]} | Skip entirely (auth/webhook/health/docs) |"
  echo "| **TOTAL** | $ROUTE_COUNT | |"
  echo ""

  for cat in REWRITE REVIEW NO-PRISMA FACTORY STANDARD BAND-3; do
    echo "## ${cat} (${COUNTS[$cat]})"
    echo ""
    if [ "$cat" = "REWRITE" ]; then
      echo "These routes reference Prisma models that don't exist in the current"
      echo "\`prisma/schema.prisma\`. They are non-functional today — every real DB"
      echo "call errors. Replace with a fresh route generated from the template."
      echo ""
    elif [ "$cat" = "FACTORY" ]; then
      echo "Use \`createRouteHandlers\` from \`src/lib/api/route-factory.ts\`."
      echo "Migration happens centrally — once route-factory.ts uses"
      echo "\`withAuthAndTenant\` / a tenant-scoped Prisma client, every route"
      echo "in this list inherits tenant isolation without per-file changes."
      echo ""
    elif [ "$cat" = "STANDARD" ]; then
      echo "Match the B3 exemplar pattern. Eligible for the automated codemod."
      echo ""
    elif [ "$cat" = "REVIEW" ]; then
      echo "Use Prisma but don't match the standard pattern (custom auth, unusual"
      echo "imports, dynamic dispatch, etc.). Human inspection required."
      echo ""
    elif [ "$cat" = "NO-PRISMA" ]; then
      echo "No Prisma reference — proxies, passthroughs, AI-only endpoints, or"
      echo "static-data responders. Need human inspection to confirm no tenant"
      echo "data is exposed."
      echo ""
    elif [ "$cat" = "BAND-3" ]; then
      echo "Intentionally outside tenancy: auth bootstrap, webhook receivers,"
      echo "health probes, OpenAPI docs, public events. No migration needed."
      echo ""
    fi

    while IFS= read -r route; do
      [ "${CATEGORY[$route]}" = "$cat" ] && echo "- \`$route\` — ${REASON[$route]}"
    done <<< "$ROUTES"
    echo ""
  done

  echo "## Next steps"
  echo ""
  echo "1. Review the **REWRITE** list. Confirm each entry should indeed be"
  echo "   regenerated from scratch (not just fixed in place)."
  echo "2. Review the **REVIEW** and **NO-PRISMA** lists. Some entries may"
  echo "   reclassify to STANDARD after a small refactor; others may move to"
  echo "   REWRITE."
  echo "3. Run \`scripts/migrate-routes.ts\` against the STANDARD list to"
  echo "   produce migrated route files in bulk."
  echo "4. For each REWRITE entry, run \`scripts/scaffold-route.ts <ModelName>\`"
  echo "   to emit a fresh schema-driven CRUD route."
} > "$OUT"

echo "Wrote $OUT"
echo "  FACTORY:   ${COUNTS[FACTORY]}"
echo "  STANDARD:  ${COUNTS[STANDARD]}"
echo "  REWRITE:   ${COUNTS[REWRITE]}"
echo "  REVIEW:    ${COUNTS[REVIEW]}"
echo "  NO-PRISMA: ${COUNTS[NO-PRISMA]}"
echo "  BAND-3:    ${COUNTS[BAND-3]}"
echo "  TOTAL:     $ROUTE_COUNT"
